import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary": "#4edea3",
        "surface": "#0f131d",
        "inverse-primary": "#494bd6",
        "surface-container-lowest": "#0a0e18",
        "primary-fixed-dim": "#c0c1ff",
        "surface-container-low": "#171b26",
        "on-background": "#dfe2f1",
        "tertiary-fixed-dim": "#ffb3ad",
        "inverse-on-surface": "#2c303b",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-secondary-fixed-variant": "#005236",
        "primary": "#c0c1ff",
        "on-surface": "#dfe2f1",
        "outline-variant": "#464554",
        "on-tertiary": "#68000a",
        "inverse-surface": "#dfe2f1",
        "on-surface-variant": "#c7c4d7",
        "primary-container": "#8083ff",
        "on-tertiary-fixed": "#410004",
        "error": "#ffb4ab",
        "on-error-container": "#ffdad6",
        "tertiary-fixed": "#ffdad7",
        "on-primary-container": "#0d0096",
        "on-primary-fixed": "#07006c",
        "tertiary": "#ffb3ad",
        "secondary-fixed": "#6ffbbe",
        "surface-container-high": "#262a35",
        "on-secondary": "#003824",
        "surface-container": "#1c1f2a",
        "secondary-container": "#00a572",
        "surface-dim": "#0f131d",
        "on-error": "#690005",
        "on-primary": "#1000a9",
        "on-tertiary-container": "#5c0008",
        "background": "#0f131d",
        "outline": "#908fa0",
        "secondary-fixed-dim": "#4edea3",
        "on-secondary-container": "#00311f",
        "surface-container-highest": "#313540",
        "error-container": "#93000a",
        "surface-tint": "#c0c1ff",
        "on-tertiary-fixed-variant": "#930013",
        "tertiary-container": "#ff5451",
        "surface-bright": "#353944",
        "on-secondary-fixed": "#002113",
        "primary-fixed": "#e1e0ff",
        "surface-variant": "#313540",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-xl": "2rem",
        "space-xs": "0.25rem",
        "margin-mobile": "1rem",
        "space-2xl": "3rem",
        "gutter-mobile": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "gutter": "1.25rem",
        "margin": "2rem",
        "space-sm": "0.5rem",
      },
      fontFamily: {
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "metric-md": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "metric-xl": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "display": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "metric-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "metric-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "400" }],
        "display": ["40px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.025em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
