import { Expense } from "@/types/expense";

export const INITIAL_EXPENSES: Omit<Expense, "id">[] = [
  {
    dia: 1,
    concepto: "Tarjeta de Crédito Banamex / Bancomer",
    categoria: "Tarjetas",
    subtitulo: "Pago para no generar intereses / mínimo",
    metodo: "Banca Móvil",
    monto: 1200.0,
    estado: "Hecho",
    mes_ano: "2026-09",
  },
  {
    dia: 1,
    concepto: "Seguro de Auto",
    categoria: "Salud",
    subtitulo: "Póliza de cobertura amplia",
    metodo: "Tarjeta Banorte",
    monto: 1500.0,
    estado: "Hecho",
    mes_ano: "2026-09",
  },
  {
    dia: 1,
    concepto: "Amazon Prime",
    categoria: "Servicios",
    subtitulo: "Suscripción mensual y streaming",
    metodo: "Tarjeta Débito",
    monto: 130.0,
    estado: "Hecho",
    mes_ano: "2026-09",
  },
  {
    dia: 5,
    concepto: "Izzi",
    categoria: "Servicios",
    subtitulo: "Internet, telefonía y televisión",
    metodo: "Banca Móvil",
    monto: 1000.0,
    estado: "Hecho",
    mes_ano: "2026-09",
  },
  {
    dia: 5,
    concepto: "Mantenimiento",
    categoria: "Vivienda",
    subtitulo: "Cuota de mantenimiento del fraccionamiento/edificio",
    metodo: "Transferencia SPEI",
    monto: 400.0,
    estado: "Hecho",
    mes_ano: "2026-09",
  },
  {
    dia: 5,
    concepto: "Agua",
    categoria: "Servicios",
    subtitulo: "Servicio de agua potable y drenaje",
    metodo: "Banca Móvil",
    monto: 500.0,
    estado: "Hecho",
    mes_ano: "2026-09",
  },
  {
    dia: 5,
    concepto: "Luz / Gas del mes",
    categoria: "Servicios",
    subtitulo: "Consumo mensual de energía y gas LP",
    metodo: "App CFE / Efectivo",
    monto: 800.0,
    estado: "Hecho",
    mes_ano: "2026-09",
  },
  {
    dia: 15,
    concepto: "Telmex",
    categoria: "Servicios",
    subtitulo: "Internet Infinitum fibra óptica",
    metodo: "Domiciliado",
    monto: 500.0,
    estado: "Hecho",
    mes_ano: "2026-09",
  },
  {
    dia: 15,
    concepto: "Agua",
    categoria: "Servicios",
    subtitulo: "Segunda cuota / servicio auxiliar de agua",
    metodo: "Banca Móvil",
    monto: 400.0,
    estado: "Hecho",
    mes_ano: "2026-09",
  },
  {
    dia: 17,
    concepto: "Mercado",
    categoria: "Vivienda",
    subtitulo: "Despensa y canasta básica familiar",
    metodo: "Efectivo / Tarjeta",
    monto: 1000.0,
    estado: "Pendiente",
    mes_ano: "2026-09",
  },
  {
    dia: 20,
    concepto: "Coppel",
    categoria: "Tarjetas",
    subtitulo: "Abono a cuenta departamental",
    metodo: "Banca Móvil",
    monto: 1000.0,
    estado: "Pendiente",
    mes_ano: "2026-09",
  },
  {
    dia: 24,
    concepto: "Tarjeta de Crédito Banamex / Bancomer",
    categoria: "Tarjetas",
    subtitulo: "Pago mensual corte 24",
    metodo: "Banca Móvil",
    monto: 1300.0,
    estado: "Pendiente",
    mes_ano: "2026-09",
  },
  {
    dia: 30,
    concepto: "Tarjeta de Crédito Santander",
    categoria: "Tarjetas",
    subtitulo: "Pago para no generar intereses",
    metodo: "Banca Móvil",
    monto: 1100.0,
    estado: "Pendiente",
    mes_ano: "2026-09",
  },
  {
    dia: 7, // Domingo representativo semanal
    concepto: "Banco Azteca (Semanal)",
    categoria: "Tarjetas",
    subtitulo: "Abono semanal cada domingo",
    metodo: "App Banco Azteca / Efectivo",
    monto: 500.0,
    estado: "Pendiente",
    mes_ano: "2026-09",
  },
];
